queries:
  - id: "1"
    description: "List All Unique SSIDs"
    query: "SELECT DISTINCT ssid FROM devices;"

  - id: "2"
    description: "List All Devices"
    query: "SELECT * FROM devices;"

  - id: "3"
    description: "Count Total Devices"
    query: "SELECT COUNT(*) AS total_devices FROM devices;"

  - id: "4"
    description: "List All Access Points"
    query: "SELECT mac AS ap_mac, ssid, encryption FROM devices WHERE device_type = 'AP';"

  - id: "5"
    description: "List Clients by Signal Strength"
    query: "SELECT mac, ssid, signal_strength FROM clients WHERE signal_strength IS NOT NULL ORDER BY signal_strength DESC;"

  - id: "6"
    description: "Count Unique SSIDs Per Encryption Type"
    query: "SELECT encryption, COUNT(DISTINCT ssid) AS ssid_count FROM devices GROUP BY encryption ORDER BY ssid_count DESC;"

  - id: "7"
    description: "Top Clients by Signal Strength"
    query: "SELECT mac, signal_strength FROM clients WHERE signal_strength IS NOT NULL ORDER BY signal_strength DESC;"

  - id: "8"
    description: "Access Points with Weak or No Encryption"
    query: "SELECT mac AS ap_mac, ssid, encryption FROM devices WHERE encryption IS NULL OR encryption = 'Open';"

  - id: "9"
    description: "Devices with Most Recent Activity"
    query: "SELECT mac, ssid, last_seen FROM devices ORDER BY last_seen DESC;"

  - id: "10"
    description: "Count of Clients Associated with Each Access Point"
    query: >
      SELECT devices.mac AS ap_mac, devices.ssid, COUNT(clients.mac) AS client_count
      FROM devices
      LEFT JOIN clients ON devices.mac = clients.associated_ap
      WHERE devices.device_type = 'AP'
      GROUP BY devices.mac, devices.ssid
      ORDER BY client_count DESC;

  - id: "11"
    description: "List All WPA-SEC Entries"
    query: "SELECT bssid, ssid, password FROM wpa_sec_results;"

  - id: "12"
    description: "WPA-SEC Entries with Matching SSID and Password Across BSSIDs"
    query: >
      SELECT ssid, password, COUNT(DISTINCT bssid) AS bssid_count
      FROM wpa_sec_results
      GROUP BY ssid, password
      HAVING bssid_count > 1
      ORDER BY bssid_count DESC;

  - id: "13"
    description: "Frequently Repeated WPA-SEC Passwords"
    query: >
      SELECT password, COUNT(*) AS usage_count
      FROM wpa_sec_results
      GROUP BY password
      ORDER BY usage_count DESC;

  - id: "14"
    description: "WPA-SEC Networks with No SSID"
    query: "SELECT bssid, password FROM wpa_sec_results WHERE ssid IS NULL OR ssid = '';"

  - id: "15"
    description: "List All Devices with Their Associated Access Points"
    query: >
      SELECT devices.ssid AS ssid, devices.mac AS ap_mac, clients.mac AS client_mac, MAX(clients.last_seen) AS last_seen
      FROM devices
      JOIN clients ON devices.mac = clients.associated_ap
      WHERE devices.ssid IS NOT NULL AND devices.ssid != ''
      GROUP BY devices.ssid, devices.mac, clients.mac
      ORDER BY devices.ssid ASC, last_seen DESC;

  - id: "16"
    description: "Devices with the Most Frequent Channel Changes"
    query: >
      SELECT mac, COUNT(DISTINCT channel) AS channel_count
      FROM devices
      WHERE channel IS NOT NULL
      GROUP BY mac
      ORDER BY channel_count DESC;

  - id: "17"
    description: "Signal Strength Distribution for Devices"
    query: >
      SELECT mac, AVG(signal_strength) AS avg_signal, MIN(signal_strength) AS min_signal, MAX(signal_strength) AS max_signal
      FROM devices
      WHERE signal_strength IS NOT NULL
      GROUP BY mac
      ORDER BY avg_signal DESC;

  - id: "18"
    description: "List All Unique Device Manufacturers"
    query: "SELECT DISTINCT manufacturer FROM devices WHERE manufacturer IS NOT NULL;"

  - id: "19"
    description: "Devices Associated with Multiple Access Points"
    query: >
      SELECT mac, COUNT(DISTINCT associated_ap) AS ap_count
      FROM clients
      GROUP BY mac
      HAVING ap_count > 1
      ORDER BY ap_count DESC;

  - id: "20"
    description: "Count of Devices by Manufacturer"
    query: >
      SELECT manufacturer, COUNT(*) AS device_count
      FROM devices
      GROUP BY manufacturer
      ORDER BY device_count DESC;